# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0011_secretkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretkey',
            options={'verbose_name': 'Секретный ключ', 'verbose_name_plural': 'Секретные ключи'},
        ),
    ]
